language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# No dependencies currently:
# install: pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
script:  python setup.py test
